export const APP_ERROR_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    DATABASE_ERROR: "DATABASE_ERROR",
    INTERNAL_ERROR: "INTERNAL_ERROR",

    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    AUTH_USER_INACTIVE: "AUTH_USER_INACTIVE",
    AUTH_USER_SUSPENDED: "AUTH_USER_SUSPENDED",
    AUTH_SESSION_NOT_FOUND: "AUTH_SESSION_NOT_FOUND",
    AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
    AUTH_SESSION_REVOKED: "AUTH_SESSION_REVOKED",
    AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
} as const;

export type AppErrorCode =
    (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];