import { APP_ERROR_CODES } from "@/server/shared/errors/error-codes";

export const AUTH_ERROR_CODES = {
    INVALID_CREDENTIALS: APP_ERROR_CODES.AUTH_INVALID_CREDENTIALS,
    USER_NOT_FOUND: APP_ERROR_CODES.AUTH_USER_NOT_FOUND,
    USER_INACTIVE: APP_ERROR_CODES.AUTH_USER_INACTIVE,
    USER_SUSPENDED: APP_ERROR_CODES.AUTH_USER_SUSPENDED,
    SESSION_NOT_FOUND: APP_ERROR_CODES.AUTH_SESSION_NOT_FOUND,
    SESSION_EXPIRED: APP_ERROR_CODES.AUTH_SESSION_EXPIRED,
    SESSION_REVOKED: APP_ERROR_CODES.AUTH_SESSION_REVOKED,
    UNAUTHENTICATED: APP_ERROR_CODES.AUTH_UNAUTHENTICATED,
    UNAUTHORIZED: APP_ERROR_CODES.AUTH_UNAUTHORIZED,
} as const;

export type AuthErrorCode =
    (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];