export const AUTH_ERROR_CODES = {
    INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    USER_INACTIVE: "AUTH_USER_INACTIVE",
    USER_SUSPENDED: "AUTH_USER_SUSPENDED",
    SESSION_NOT_FOUND: "AUTH_SESSION_NOT_FOUND",
    SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
    SESSION_REVOKED: "AUTH_SESSION_REVOKED",
    UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
} as const;

export type AuthErrorCode =
    (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];